# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movieId',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
