# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_user_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_ref_id',
        ),
    ]
